support for sendmail
sunfoxcz/ansible-dkim pull request #8
Opened 2020-08-06 02:01 UTC by Sebseb01

### Hello, i have used your role, but with sendmail. i send to you my modification, i dont know if your interested. (sorry if some basic error i'm a pretty new user of ansible) thanks in advance.

2020-08-07 13:37 UTC, foxycode commented
@Sebseb01 Those sendmail refresh command looks pretty foreign to me. Are you using Ubuntu? This role was meant for Debian/Ubuntu only. Is this common way to refresh sendmail? Is make installed automaticcally when you have sendmail on your system? I believe it isn't.

2020-08-07 14:37 UTC, Sebseb01 commented
It's beacause sendmail use m4 macro for generate sendmail.cf 


m4 and make are in dependencies of package sendmail (and specialy on sendmail-cf)

I have use your role and testmy pull-request on Debian stretch and Buster,  i don't have any reason to think it will  not the same on ubuntu. I wiil be test later and commit a fix if it doesn't work.

2020-08-07 14:40 UTC, foxycode commented
Let me know when you test it then ;)

2020-08-07 17:11 UTC, ulvida commented
Heureux de savoir que ce travail a servi, et plus encore de constater que l'on travaille sur des technologies accessibles! 

Thanks for your contribution! I agree with @foxycode to test well before merging, but think it's good to integrate other MTAs' management in the role. Maybe we can help to test your PR in Ubuntu.

2020-08-07 17:28 UTC, Sebseb01 commented
I have just tested with Xenial and it perfectly works

2020-08-07 22:18 UTC, Sebseb01 commented
I have tried to use travis without success for the moment.

Je contribue avec plaisire, votre "code" d'une grande qualité, m'apprend quantités de choses.
Le texte brute est très accessible, jai la chance d'avoir choisi ce métier (avant le handicap), qui est aussi une passion.

;-)

2020-08-07 23:19 UTC, foxycode commented
Guys, I tried to test with Debian before with o success. It's different to run role on system than run role on system you want to setup. I had problem to add Debian to test targets because of default Ansible version,  If you figure it out, it would be great!

2020-08-08 11:08 UTC, Sebseb01 commented
Ok, it was just a typping error. Please let me know if you have some issue.

For travis on debian buster you can remove the ppa ... in debian repo it's ansible 2.7 and i think your role work fine with this version. or activate backport for 2.9. and for stretch you have 2.7 in backports.

2020-08-08 16:39 UTC, foxycode commented
@Sebseb01 I don't use Debian, so it would great if you could fix tests for Debian. Looks like you have experience.

Also, add sendmail test for all Ubuntu version in `.travis.yml` please.

2020-08-09 00:43 UTC, Sebseb01 commented
Ok @foxycod, I have added and passed of all ubuntu version and debian too.

I hope this can help you.

2020-08-09 15:05 UTC, foxycode requested changes
You did a great work, thank you! Before I merge it, need to to fix few minor details I hope.

* Update test env as I suggested please, to test `sendmail` with `Ubuntu` too.
* I added `jessie` too, because it should be supported. If you can't make it work on `jessie`, remove `jessie` from supported versions in `meta/main.yml` please.

Otherwise it looks very good :+1:

2020-08-09 15:05 UTC, foxycode commented on .travis.yml
> +    playbook: sendmail.yml
Test sendmail with Ubuntu too please:
```
  - distribution: ubuntu
    version: xenial
    playbook: same_key.yml
  - distribution: ubuntu
    version: xenial
    playbook: different_keys.yml
  - distribution: ubuntu
    version: xenial
    playbook: sendmail.yml
  - distribution: ubuntu
    version: bionic
    playbook: same_key.yml
  - distribution: ubuntu
    version: bionic
    playbook: different_keys.yml
  - distribution: ubuntu
    version: bionic
    playbook: sendmail.yml
  - distribution: ubuntu
    version: focal
    playbook: same_key.yml
  - distribution: ubuntu
    version: focal
    playbook: different_keys.yml
  - distribution: ubuntu
    version: focal
    playbook: sendmail.yml
  - distribution: debian
    version: jessie
    playbook: same_key.yml
  - distribution: debian
    version: jessie
    playbook: different_keys.yml
  - distribution: debian
    version: jessie
    playbook: sendmail.yml
  - distribution: debian
    version: stretch
    playbook: same_key.yml
  - distribution: debian
    version: stretch
    playbook: different_keys.yml
  - distribution: debian
    version: stretch
    playbook: sendmail.yml
  - distribution: debian
    version: buster
    playbook: same_key.yml
  - distribution: debian
    version: buster
    playbook: different_keys.yml
  - distribution: debian
    version: buster
    playbook: sendmail.yml
```

2020-08-10 20:50 UTC, Sebseb01 commented
Ok i have edit the travis.yml 

I think it's a good idea to remove support of  Jessie this version is no more supported by the LTS project and it very old now.

2020-08-11 13:21 UTC, foxycode commented on meta/main.yml
> +    - postfix    - postfix
This is probably typo

2020-08-12 16:18 UTC, foxycode commented
Can you please look why `xenial` tests failed?

2020-08-15 00:42 UTC, Sebseb01 commented
Hello, I have created a Xenial  container in my local test, and manually running test. It just work. I don't understand why this failure apear after i have edit "meta".

And why systemd can't start dkim service ... 

i don't have idea for the moment

2020-08-17 10:02 UTC, foxycode commented
Ok, since it worked for you, I will merge it anyway.

Many thanks for your contributtion1

2020-08-17 10:03 UTC, merged